language: java

#jdk:
#    - oraclejdk8

addons:
 apt:
   packages:
   - ant
   - ant-optional

before_install:
  - pushd .
  - export BEAGLE_BRANCH=hmc-clock
  - mkdir -p ${BEAGLE_LIB}
  - git clone -b ${BEAGLE_BRANCH} https://github.com/beagle-dev/beagle-lib.git ${BEAGLE_BUILD}
  - cd ${BEAGLE_BUILD}
  - ./autogen.sh
  - ./configure --without-cuda --without-opencl --prefix=${BEAGLE_LIB}
  - make
  - make install
  - export LD_LIBRARY_PATH=${BEAGLE_LIB}/lib
  - ls ${BEAGLE_LIB}/lib
  - popd

script:
  - ant dist
  - cd ci; ./test.sh
  - cd ..; ant junit

env:
  global:
    - BEAGLE_BUILD=$HOME/beagle-build
    - BEAGLE_LIB=$HOME/beagle-lib
